
on:
  push:
    branches:
    - 'feat/repo-merge-change'
      #- 'develop'

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger exiting circleci job
        uses: zivkaziv/circleci-trigger-github-action@master
        with:
          token: ${{ secrets.CCI_DOCS_TOKEN }}
          branch: dev/circleci
          org: rammerai
          repo: docs-v1
